api:
    resource: '@ApiBundle/Controller/'
    type: annotation

article_get:
    path: /article/{id}
    defaults:
        _controller: ApiBundle:Article:get
    requirements:
        id: '\d+'

article_add:
    path: /article/add/{name}
    defaults:
        _controller: ApiBundle:Article:add
    requirements:
        name: '[a-zA-Z-\d]+'

article_list:
    path: /article/list
    defaults:
        _controller: ApiBundle:Article:list




comment_get:
    path: /comment/{id}
    defaults:
        _controller: ApiBundle:Comment:get
    requirements:
        id: '\d+'

comment_add:
    path: /comment/add
    defaults:
        _controller: ApiBundle:Comment:add


login:
    path: /login
    defaults:
        _controller: ApiBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout
