services:
    api.article:
        class: ApiBundle\Service\ArticleService
        arguments: ["@doctrine.orm.entity_manager"]
        public: true

    # user:
    #     class: ApiBundle\Service\UserService
    #     arguments: ["@service_container"]
    #     public: true
    #
    # comment:
    #     class: ApiBundle\Service\CommentService
    #     arguments: ["@service_container"]
    #     public: true
